# Team: Group 15  
member: Yunlong Ou, Yunzhuo Liu, Yuyun Zhen, Te-Hsin Kung, Joshua Liu

## Heart disease dataset

Dataset: Indicators of Heart Disease  
<br>
Location: https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease  
<br>
Description: This project leverages the 2022 Key Indicators of Heart Disease dataset, sourced from the CDC's Behavioral Risk Factor Surveillance System (BRFSS). This extensive dataset includes health-related survey responses from over 400,000 U.S. adults, covering a wide range of variables that relate to heart disease. These variables include critical risk factors such as high blood pressure, high cholesterol, smoking habits, diabetes, obesity, physical inactivity, and alcohol consumption. These indicators allow us to explore patterns that might help predict the likelihood of heart disease.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

In [3]:
heart_disease = pd.read_csv('https://media.githubusercontent.com/media/jliu3627/Heart_Disease_Project/refs/heads/main/data/2022/heart_2022_with_nans.csv')

### Part 1

#### Basic information about the dataset:

In [4]:
heart_disease.info()
heart_disease.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445132 entries, 0 to 445131
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      445132 non-null  object
 1   Sex                        445132 non-null  object
 2   GeneralHealth              443934 non-null  object
 3   PhysicalHealthDays         434205 non-null  float64
 4   MentalHealthDays           436065 non-null  float64
 5   LastCheckupTime            436824 non-null  object
 6   PhysicalActivities         444039 non-null  object
 7   SleepHours                 439679 non-null  float64
 8   RemovedTeeth               433772 non-null  object
 9   HadHeartAttack             442067 non-null  object
 10  HadAngina                  440727 non-null  object
 11  HadStroke                  443575 non-null  object
 12  HadAsthma                  443359 non-null  object
 13  HadSkinCancer              441989 non-null  object
 14  HadCOPD                    442913 non-null  object
 15  HadDepressiveDisorder      442320 non-null  object
 16  HadKidneyDisease           443206 non-null  object
 17  HadArthritis               442499 non-null  object
 18  HadDiabetes                444045 non-null  object
 19  DeafOrHardOfHearing        424485 non-null  object
 20  BlindOrVisionDifficulty    423568 non-null  object
 21  DifficultyConcentrating    420892 non-null  object
 22  DifficultyWalking          421120 non-null  object
 23  DifficultyDressingBathing  421217 non-null  object
 24  DifficultyErrands          419476 non-null  object
 25  SmokerStatus               409670 non-null  object
 26  ECigaretteUsage            409472 non-null  object
 27  ChestScan                  389086 non-null  object
 28  RaceEthnicityCategory      431075 non-null  object
 29  AgeCategory                436053 non-null  object
 30  HeightInMeters             416480 non-null  float64
 31  WeightInKilograms          403054 non-null  float64
 32  BMI                        396326 non-null  float64
 33  AlcoholDrinkers            398558 non-null  object
 34  HIVTesting                 379005 non-null  object
 35  FluVaxLast12               398011 non-null  object
 36  PneumoVaxEver              368092 non-null  object
 37  TetanusLast10Tdap          362616 non-null  object
 38  HighRiskLastYear           394509 non-null  object
 39  CovidPos                   394368 non-null  object
dtypes: float64(6), object(34)
memory usage: 135.8+ MB

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,NaN,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,NaN,No,...,1.60,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,NaN,No,...,1.57,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,NaN,No,...,1.57,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No
5,Alabama,Male,Poor,1.0,0.0,Within past year (anytime less than 12 months ...,No,7.0,NaN,Yes,...,1.80,84.82,26.08,No,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No
6,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,62.60,22.96,Yes,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
7,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,1.63,73.48,27.81,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
8,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,NaN,No,...,1.70,NaN,NaN,No,Yes,No,No,"Yes, received tetanus shot but not sure what type",No,No
9,Alabama,Female,Good,1.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.68,81.65,29.05,Yes,NaN,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

#### Drop missing values

In [5]:
# check for missing values
heart_disease.isnull().sum()
# drop rows with missing values.
data_droppedna = heart_disease.dropna()
data_droppedna.isnull().sum()

State                        0
Sex                          0
GeneralHealth                0
PhysicalHealthDays           0
MentalHealthDays             0
LastCheckupTime              0
PhysicalActivities           0
SleepHours                   0
RemovedTeeth                 0
HadHeartAttack               0
HadAngina                    0
HadStroke                    0
HadAsthma                    0
HadSkinCancer                0
HadCOPD                      0
HadDepressiveDisorder        0
HadKidneyDisease             0
HadArthritis                 0
HadDiabetes                  0
DeafOrHardOfHearing          0
BlindOrVisionDifficulty      0
DifficultyConcentrating      0
DifficultyWalking            0
DifficultyDressingBathing    0
DifficultyErrands            0
SmokerStatus                 0
ECigaretteUsage              0
ChestScan                    0
RaceEthnicityCategory        0
AgeCategory                  0
HeightInMeters               0
WeightInKilograms            0
BMI                          0
AlcoholDrinkers              0
HIVTesting                   0
FluVaxLast12                 0
PneumoVaxEver                0
TetanusLast10Tdap            0
HighRiskLastYear             0
CovidPos                     0
dtype: int64

#### drop duplicate rows

In [6]:
# Drop duplicate rows
df_no_duplicates = data_droppedna.drop_duplicates()
print(df_no_duplicates.shape)

(246013, 40)

#### drop outliers

In [10]:
def remove_outliers(df):
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        # Use .loc to avoid the SettingWithCopyWarning
        df.loc[:, col] = df[col].clip(lower_bound, upper_bound)

    return df

df_no_outliers = remove_outliers(df_no_duplicates)

#### encoding categorical variables

In [15]:
def encode_catgorical_variables(df):
  categorical_cols = df.select_dtypes(include = ['object']).columns
  endoding_map = {}
  for col in categorical_cols:
    df[col], uniques = pd.factorize(df[col])
    endoding_map[col] = dict(enumerate(uniques))
  return df, endoding_map

df_encoded, encoding_map = encode_catgorical_variables(df_no_outliers)

print(df_encoded.head())
for col, mapping in encoding_map.items():
  print(f"{col}: {mapping}")

     State  Sex  GeneralHealth  PhysicalHealthDays  MentalHealthDays  \
342      0    0              0                 4.0               0.0
343      0    1              0                 0.0               0.0
345      0    1              0                 0.0               0.0
346      0    0              1                 5.0               0.0
347      0    0              2                 3.0              10.0

     LastCheckupTime  PhysicalActivities  SleepHours  RemovedTeeth  \
342                0                   0         9.0             0
343                0                   0         6.0             0
345                0                   0         8.0             1
346                0                   0         9.0             0
347                0                   0         5.0             2

     HadHeartAttack  ...  HeightInMeters  WeightInKilograms    BMI  \
342               0  ...            1.60              71.67  27.99
343               0  ...            1.78              95.25  30.13
345               0  ...            1.85             108.86  31.66
346               0  ...            1.70              90.72  31.32
347               0  ...            1.55              79.38  33.07

     AlcoholDrinkers  HIVTesting  FluVaxLast12  PneumoVaxEver  \
342                0           0             0              0
343                0           0             0              0
345                1           0             1              0
346                0           0             0              0
347                0           0             0              0

     TetanusLast10Tdap  HighRiskLastYear  CovidPos
342                  0                 0         0
343                  1                 0         0
345                  2                 0         1
346                  2                 0         1
347                  2                 0         0

[5 rows x 40 columns]